#!/usr/bin/env bash
#dig a given domain


report_print()
{
    echo The subdomain $1 is a $2 record and points to $3
}

if [ $# -eq 1 ]
    then
        sub_domains="www lb-01 web-01 web-02"
        for i in $sub_domains; do
            ip="$(dig $i.$1 | grep -A1 'ANSWER SECTION:' | awk '{print $5}')"
            rtype="$(dig $i.$1 | grep -A1 'ANSWER SECTION:' | awk '{print $4}')"
            report_print "$i" "$rtype" "$ip"
        done
elif [ $# -eq 2 ]
    then
        ip="$(dig $2.$1 | grep -A1 'ANSWER SECTION:' | awk '{print $5}')"
        rtype="$(dig $2.$1 | grep -A1 'ANSWER SECTION:' | awk '{print $4}')"
        report_print "$2" "$rtype" "$ip"
fi
