#!/usr/bin/env bash
# This script creates a file, handles the kill, SIGINT signal.
#deletes the file and terminates itself with a SIGQUIT or SIGTERM signal
x=1
echo $$ > /var/run/holbertonscript.pid
while [ $x -le 1 ]
do
 echo "To infinity and beyond"
 sleep 2
 trap 'echo "I hate the kill command"; rm /var/run/holbertonscript.pid; exit' 15
 trap 'echo "Y U no love me?!"' 2
 trap 'rm /var/run/holbertonscript.pid; exit' 3
done
