#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
STR="Holberton School"
x=1
while [ $x -le 10 ]
do
 if [ $x -eq 4 ]
 then
   echo "bad luck"
 elif [ $x -eq 8 ]
 then
   echo "good luck"
 else
   echo "$STR"
 fi
 x=$(( x + 1))
done
