#!/usr/bin/env bash
#Script that configures an Ubuntu, localhost 127.0.0.2, facebook.com 8.8.8.8
sed 's/127.0.0.1/127.0.0.2/' /etc/hosts > ~/hosts.new
echo "8.8.8.8   facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
rm ~/hosts.new
