#!/usr/bin/env bash
#easy method to do a server configuration for a nginx user
sudo pkill apache2
sudo chmod 777 /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start
