#!/usr/bin/env bash
#Server configuration for nginx user
sudo pkill apache2
sudo chmod 777 /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start
